import type { Metadata } from "next";
import NavBar from "@/app/components/Navbar/Navbar";

import "./globals.css";

export const metadata: Metadata = {
  title: "Swerve VOD Management System",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
    
        <body> 
           
            {children}

        </body>
    </html>
  );
}
