//import { VideoTypes } from "@/database/models/definitions/Video";
import { SeriesModel } from "./SeriesModel";

export type VideoModel = {
    guid: string;
    title: string;
    licensor: string;
    type: string;
    synopsis: string;
    shortSynopsis: string;
    seriesTitle: string;
    series?: SeriesModel;
    season?: number;
    episode?: number;
    rating: string;
    duration: number;
    releaseDate: string;
    countryOfOrigin: string;
    genre: string;
    tags: string;
    mainCast: string;
    filePath: string;
    originalVideoFilename: string;
    videoFilename: string;
    captionsFilename: string;
    artFilename: string;
    women: boolean;
    TMSID: string;
    adBreaks: string;
    slingCategory: string;
    slingId: string;
    rightsStart: string;
    rightsEnd: string;
    rightsTerritory: string;
    frequency: string;
    brandedVOD: string;
    unbrandedVOD: string;
    thirdPartyLinear: string;
    fubo: string;
    sling: string;
    xumo: string;
    amazon: string;
    pluto: string;
    roku: string;
    vizio: string;
    fsn: string;
    rsc: string;
    selected: boolean;
}